spring:
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 10MB  # 한 번에 최대 업로드 가능 용량
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${LOCAL_HOST}:${DB_PORT}/${DB_DATABASE_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

# HS256 ????? ??? ??? ??? 256bit, ? 32byte ??? secret key? ???? ??.
# Base64 ? ???? ? ??
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
kakao:
  key: ${KAKAO_SEARCH_KEY}
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

data:
  redis:
    host: ${REDIS_HOST}
    port: 6379


cloud:
  aws:
    s3:
      bucket: ${BUCKET}
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}

  admin-token: ${ADMIN_TOKEN}

  kakao-login:
    key: ${KAKAO_LOGIN_KEY}